name: Validate Terraform Docs

on:
  pull_request:
    
permissions:
    contents: read

jobs:
  RunTerraformDocsValidation:
    name: Run Terraform-docs
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Install terraform-docs v0.19.0
        run: |
          curl -sSL https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz \
            | tar -xzC /usr/local/bin terraform-docs

      - name: Check module README.md is up to date
        run: |
          terraform-docs markdown table modules/appstream2-automation-infra \
            > modules/appstream2-automation-infra/expected.md
          if ! diff -u modules/appstream2-automation-infra/README.md \
                     modules/appstream2-automation-infra/expected.md; then
            echo "📖 modules/appstream2-automation-infra/README.md is out of date. Please run:"
            echo "    terraform-docs markdown table modules/appstream2-automation-infra \\"
            echo "      --output-file modules/appstream2-automation-infra/README.md \\"
            echo "      --output-mode inject"
            exit 1
          fi
